name: Github Actions folder3

on:
  push:
    branches:
      - main
    paths:
      - 'folder3/**'
      - 'shared-lib/**'
  pull_request:
    paths:
      - 'fodler1/**'
      - 'shared-lib/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cat text.txt file inside folder3
        run: |
          cd folder3
          ls
          cat text.txt

      - name: Echo commit SHA
        run: |
          echo "Short SHA: $(git rev-parse --short $GITHUB_SHA)"
          echo "Full SHA: $GITHUB_SHA"
          echo "Branch: $GITHUB_REF_NAME"
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Workflow: $GITHUB_WORKFLOW"
          echo "Run ID: $GITHUB_RUN_ID"
          echo "Run Number: $GITHUB_RUN_NUMBER"